export const SET_OFFCANVAS_OPEN = 'SET_OFFCANVAS_OPEN';
export const FETCH_SINGLE_ITEM = 'FETCH_SINGLE_ITEM';
export const SET_SINGLE_ITEM = 'SET_SINGLE_ITEM';
export const SET_SHOW_LOADER = 'SET_SHOW_LOADER';
export const SET_SHOW_ERROR = 'SET_SHOW_ERROR';

