export const SET_OFFCANVAS_OPEN = 'SET_OFFCANVAS_OPEN';
export const FETCH_SINGLE_ITEM = 'FETCH_SINGLE_ITEM';
export const SET_SINGLE_ITEM = 'SET_SINGLE_ITEM';
export const SHOW_SINGLE_ITEM_LOADER = 'SHOW_SINGLE_ITEM_LOADER';
export const SHOW_SINGLE_ITEM_ERROR = 'SHOW_SINGLE_ITEM_ERROR';

